### ISSUE TITLE
101% adoption?

### ISSUE THREAD

**Issue by mteam88** [Anish-Agnihotri/mevboost.org#12]
Just saw this:
![image](https://user-images.githubusercontent.com/84196639/223847808-5c6236cb-c7a0-47b7-bf15-5881ca59cb8d.png)
This is obviously a bug...

**Comment by Anish-Agnihotri** [comment]
Yep—thanks for flagging, will give the statistics another look and update.

**Comment by Anish-Agnihotri** [comment]
This is now fixed. It looks like some relays (Ultra Sound Relay & Agnostic Relay, for example) co-report relayed blocks (duplicating slots), so the total number of relayed blocks was > total possible. Fixed with some quick de-duplication.

Thanks for flagging.

**Comment by mteam88** [comment]
No problem. Love your work, happy I could help in a small way.
