### ISSUE TITLE
missed 2 blocks from manifold

### ISSUE THREAD

**Issue by maVexxe** [Anish-Agnihotri/mevboost.org#2]
manifold reports 5 payloads delivered on https://mainnet-relay.securerpc.com/ but mevboost.org only 3
the 2 skipped ones are https://mainnet-relay.securerpc.com/relay/v1/data/bidtraces/proposer_payload_delivered?slot=4737594 and https://mainnet-relay.securerpc.com/relay/v1/data/bidtraces/proposer_payload_delivered?slot=4737981

**Comment by Anish-Agnihotri** [comment]
Thanks—this was patched up during a re-sync and cleanup.
