### ISSUE TITLE
Sliding window relay data API

### ISSUE THREAD

**Issue by aratz-lasa** [Anish-Agnihotri/mevboost.org#5]
Hello,

First of all, amazing work! Your website is amazing, and I'm sure is attracting a lot of traffic.

I open this issue because it is known that the relay data API of Blocknative has a sliding window, so that it only shows the data of the last 72h. Consequently, Blocknative is showing sudden drops in its block amounts in this website. I wonder if this could be fixed somehow. I have been looking to the code, but I'm not sure what is causing this behaviour.

Do you have any idea?

Thank you!
Aratz

**Comment by Anish-Agnihotri** [comment]
Thanks for flagging—I'm planning on writing a new indexer that doesn't rely on Relay Data APIs and instead pulls directly from chain. Will keep you updated on if that resolves Blocknative's payload counts.

**Comment by Anish-Agnihotri** [comment]
Out of curiosity, though, any reason why you use a sliding window?

**Comment by aratz-lasa** [comment]
Thanks for your fast reply! I appreciate if you keep me updated, and let me know if I can help in any way.

> Out of curiosity, though, any reason why you use a sliding window?

Well it's basically for efficiency. The data API was initially intended for adding observability into the relays, and make them trustworthy. So, validators query the relay Data APIs after every interaction to check that they are correctly behaving. Therefore, we didn't expect the need for long-term storage.

Moreover, we use a sliding window because we don't want to store data unlimitedly, since that is not a requirement for the PBS protocol.

**Comment by aratz-lasa** [comment]
Hello again @Anish-Agnihotri ! Your website is becoming more popular every day, so congrats again!

In the following days we are gonna remove the sliding window and backfill the old data. Will your indexer automatically detect this?

**Comment by Anish-Agnihotri** [comment]
I can re-run the indexer for Blocknative data if you just ping me on this thread. Glad to see you are backfilling the data, will make the calculations much more accurate!

**Comment by aratz-lasa** [comment]
@Anish-Agnihotri We just finished backfilling the data and removing the sliding window!

Here is useful information for your indexer:

- Oldest delivered slot: 4710139
- Newest delivered slot: 4961495

Thank you in advance for everything! Could you let me know when you run it?

**Comment by Anish-Agnihotri** [comment]
Sorry for the delay; the backfilled data should now be imported. Thank you!
